[2022-04-18 15:07:17,491] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest manual__2022-04-18T15:07:12.555700+00:00 [queued]>
[2022-04-18 15:07:17,502] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: LocalIngestionDag.ingest manual__2022-04-18T15:07:12.555700+00:00 [queued]>
[2022-04-18 15:07:17,503] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-04-18 15:07:17,503] {taskinstance.py:1239} INFO - Starting attempt 1 of 1
[2022-04-18 15:07:17,503] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-04-18 15:07:17,516] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): ingest> on 2022-04-18 15:07:12.555700+00:00
[2022-04-18 15:07:17,521] {standard_task_runner.py:52} INFO - Started process 493 to run task
[2022-04-18 15:07:17,525] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'LocalIngestionDag', 'ingest', 'manual__2022-04-18T15:07:12.555700+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/data_ingestion_local.py', '--cfg-path', '/tmp/tmpvho1268p', '--error-file', '/tmp/tmpgvh_f0j6']
[2022-04-18 15:07:17,526] {standard_task_runner.py:77} INFO - Job 71: Subtask ingest
[2022-04-18 15:07:17,620] {logging_mixin.py:109} INFO - Running <TaskInstance: LocalIngestionDag.ingest manual__2022-04-18T15:07:12.555700+00:00 [running]> on host 0fb3f3a72b51
[2022-04-18 15:07:17,671] {warnings.py:110} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152: AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
  warnings.warn(_create_deprecation_warning(key, self._deprecation_replacements[key]))

[2022-04-18 15:07:17,703] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=LocalIngestionDag
AIRFLOW_CTX_TASK_ID=ingest
AIRFLOW_CTX_EXECUTION_DATE=2022-04-18T15:07:12.555700+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-04-18T15:07:12.555700+00:00
[2022-04-18 15:07:17,704] {logging_mixin.py:109} INFO - yellow_taxi_2022_04 /opt/***/output_2022-04.csv 2022-04-18T15:07:12.555700+00:00
[2022-04-18 15:07:20,804] {logging_mixin.py:109} INFO - connection established successfully, inserting data...
[2022-04-18 15:07:21,322] {taskinstance.py:1700} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_script.py", line 22, in ingest_callable
    df.tpep_pickup_datetime = pd.to_datetime(df.tpep_pickup_datetime)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'tpep_pickup_datetime'
[2022-04-18 15:07:21,342] {taskinstance.py:1277} INFO - Marking task as FAILED. dag_id=LocalIngestionDag, task_id=ingest, execution_date=20220418T150712, start_date=20220418T150717, end_date=20220418T150721
[2022-04-18 15:07:21,359] {standard_task_runner.py:92} ERROR - Failed to execute job 71 for task ingest
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1329, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1455, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1511, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 185, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_script.py", line 22, in ingest_callable
    df.tpep_pickup_datetime = pd.to_datetime(df.tpep_pickup_datetime)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/generic.py", line 5487, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'tpep_pickup_datetime'
[2022-04-18 15:07:21,389] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-18 15:07:21,431] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
